### ISSUE TITLE
Unclear how to get user

### ISSUE THREAD

**Issue by emirkin** [google/google-auth-library-ruby#85]
This is an issue with documentation. Both examples assume that `user_id` is known. What if it isn't, i.e. if I am actually doing SSO with this flow?

**Comment by ernie** [comment]
@emirkin I stumbled on your issue here last week when I was looking into doing something similar. I'm sure by now you've found the answer, but in case someone else winds up here: what you're looking for is the google-api-client gem. In my case, I was looking for the e-mail address of the user associated with the application default credentials.

Here's a simple version of that:

```ruby
require 'google/apis/oauth2_v2'

auth = Google::Auth.get_application_default
oauth = Google::Apis::Oauth2V2::Oauth2Service.new.tap { |service|
  service.authorization = auth
}
email = oauth.get_userinfo(fields: 'email').email
puts "Application default user is #{email}"
```

**Comment by bantini** [comment]
Thank you @ernie for the solution. I am closing this issue now assuming the problem has been solved.
