### ISSUE TITLE
Add custom params to the callback url

### ISSUE THREAD

**Issue by mustela** [google/google-auth-library-ruby#94]
Hi all!

It seems I can't find a way to set some custom query params to the callback url. I've tried using `state`, but if I do that I'm getting `Invalid redirect_uri contains reserved response param state` from Google... and I can't find anything in the code around it. 

Is there any way to send a custom param and have that back in the callback url?

Thanks

**Comment by AdityaAnand1** [comment]
Did you figure out how to do this?!

I want google to send callback to `website.com/callback/john` so that I can authorize `john`. But my website isn't only for `john` and google doesn't let you use wildcards for some reason. And so here I am, trying to figure out how to uniquely identify users with google plus auth when doing so expressly forbidden by the archaic API rules.

This is literally the only google result for "Invalid redirect_uri contains reserved response param state".... aaand it's a closed issue. Please be alive.

**Comment by mustela** [comment]
What you can use is the `state` attribute, so you could so something like `state: "client=john"` when requesting to google auth, and thats what you will get in the response too.
